apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rbac
  namespace: default

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx-rbac

  template:
    metadata:
      labels:
        app: nginx-rbac

    spec:
      securityContext:
        fsGroup: 1500

      containers:
      - name: nginx
        image: anrs125/nginx:v34

        ports:
        - containerPort: 80

        securityContext:
          allowPrivilegeEscalation: true

          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
              - CHOWN
              - SETUID
              - SETGID
              - DAC_OVERRIDE
              - FOWNER

        volumeMounts:

        # Sensitive files from Kubernetes Secret
        - name: sensitive-files
          mountPath: /etc/nginx/sensitive
          readOnly: true

        # Persistent shadow database
        - name: shadow-pvc
          mountPath: /data

      volumes:

      # Kubernetes Secret
      - name: sensitive-files
        secret:
          secretName: nginx-sensitive-secret
          defaultMode: 0400

      # PVC
      - name: shadow-pvc
        persistentVolumeClaim:
          claimName: nginx-shadow-pvc
